# Generated by Django 6.1 on 2026-08-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('publication_year', models.IntegerField()),
                ('category', models.CharField(choices=[('NOVEL', 'Novela'), ('SCIENCE', 'Ciencia'), ('HISTORY', 'Historia'), ('FANTASY', 'Fantasía'), ('TECHNOLOGY', 'Tecnología'), ('OTHER', 'Otros')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Prestado'), ('MAINTENANCE', 'Mantenimiento')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
