# Generated by Django 6.1 on 2026-08-15 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOAN_CREATED', 'Préstamo Creado'), ('LOAN_RETURNED', 'Préstamo Devuelto'), ('BOOK_ADDED', 'Libro Registrado')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
